"""add embeddings to material chunks

Revision ID: cbb5f8e8c075
Revises: 6f04eab018cc
Create Date: 2026-07-30 20:12:11.908492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb5f8e8c075'
down_revision: Union[str, Sequence[str], None] = '6f04eab018cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_chunks', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_chunks', 'embedding')
    # ### end Alembic commands ###
